parameters:
    linkin_enum_property.twig_extension.class: Linkin\Bundle\EnumPropertyBundle\Twig\EnumPropertyExtension

services:
    linkin_enum_property.twig_extension:
        class:      '%linkin_enum_property.twig_extension.class%'
        tags:
            - { name: twig.extension }
